# Generated by Django 4.1.3 on 2022-11-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_personname_name_remove_resource_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetranslation',
            name='pub_date',
        ),
    ]
