# Generated by Django 4.1.3 on 2022-11-12 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_remove_resourcetranslation_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetranslation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 11, 13, 6, 475924, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
