# Generated by Django 4.1.3 on 2022-11-12 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_resourcetranslation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetranslation',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='resource',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 18, 41, 39, 914894, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
