# Generated by Django 4.1.3 on 2022-11-14 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_remove_resourcetranslation_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='key_competence',
            field=models.CharField(choices=[('li', 'Literacy'), ('mu', 'Multilingual'), ('ma', 'Mathematical, science, technology, engineering'), ('di', 'Digital'), ('pe', 'Personal, social, learning to learn'), ('ci', 'Citizenship'), ('en', 'Entrepreneurship'), ('cu', 'Cultural awareness and expression')], default='di', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='level',
            field=models.CharField(choices=[('be', 'Beginner'), ('in', 'Intermediate'), ('ad', 'Advanced'), ('mu', 'Multiple')], default='be', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcetranslation',
            name='url',
            field=models.SlugField(default='www.google.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 15, 31, 51, 893197, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
