# Generated by Django 4.1.3 on 2022-11-16 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_alter_resource_key_competence_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonName',
        ),
        migrations.AlterField(
            model_name='resource',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 18, 32, 20, 442672, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
