# Generated by Django 4.1.3 on 2022-11-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personname',
            old_name='your_name',
            new_name='name',
        ),
    ]
