# Generated by Django 4.1.3 on 2022-11-12 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_resourcetranslation_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personname',
            name='name',
            field=models.CharField(default='Sonia', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcetranslation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 17, 15, 18, 177760, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='PersonNameTranslation',
        ),
    ]
