# Generated by Django 4.1.3 on 2022-11-14 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_resource_key_competence_resource_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 15, 39, 59, 515113, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='resourcetranslation',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
